pipeline {
    agent any
    tools {
        maven "maven"
    }
    triggers {
        pollSCM 'H/2 * * * *'
    }
    stages {
        stage("Build") {
            steps {
                sh "mvn clean install"
            }
        }
    }
}